features:
  prevent-water-break: true
  prevent-water-flow: false
  drop-spawners: true
  spawner-float-up: true

tuning:
  spawner-float-velocity-y: 0.35
  wither-flow-radius: 20.0
  spawner-drop-chance: 0.5
