name: WaterSafeWither
version: '1.0'
main: ro.puk3p.waterSafeWither.WaterSafeWither
authors: [ Puk3p ]
description: Prevents wither from breaking water and prevents water from flowing after explosions.

